FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
	build-essential \
	bison \
	flex \
	libssl-dev \
	bc
# get complete version string
RUN apt update && apt install -y git
# dev
RUN apt-get update && apt-get install -y ncurses-dev
WORKDIR /kernel
CMD ["/bin/bash"]
